hackathon/urls.py
from hackathon import views
from django.urls import path

urlpatterns = [
    path('create/', views.create, name='create'),
    path('hackathons/', views.hackathons, name='hackathons'),
    path('register_hack/', views.register_hack, name='register_hack'),
    path('my_hackathons/', views.my_hackathons, name='my_hackathons'),
    path('register_hack/<int:hack_id>/', views.register_hack, name='register_hack'),
]

hackify/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('', include('hackathon.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('submission.urls')),
]

home/urls.py
from home import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path("login/", views.custom_login, name="login"),
    path("logout/", views.custom_logout, name="logout"),
    path('accounts/login/', views.custom_login, name="login")
]

hackathon/models.py
from django.db import models


class Hackathon(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()
    sub_typ = models.CharField(max_length=100)
    start = models.DateField()
    end = models.DateField()
    reward = models.DecimalField(max_digits=8, decimal_places=2)
    prize = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.title

home/models.py
from hackathon.models import Hackathon
from django.db import models
from django.contrib.auth.models import User


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

submission/models.py
from django.db import models
from django.contrib.auth.models import User
from hackathon.models import Hackathon


class DataSubmission(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=100, null=False, blank=False)
    summ = models.CharField(max_length=500, null=False, blank=True)
    file = models.FileField(upload_to='static/')
    link = models.URLField()
    image = models.ImageField(upload_to='static/')
    timestamp = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    hack = models.ForeignKey(Hackathon, on_delete=models.CASCADE)

    def __str__(self):
        return f"Submission #{self.id}"

create/views.py
from django.shortcuts import render, redirect
from create.models import Hackathon


def create(request):

    if request.method == 'POST':
        title = request.POST.get('title')
        desc = request.POST.get('desc')
        bg_img = request.FILES['bg_img']
        hack_img = request.FILES['hack_img']
        sub_typ = request.POST.get('sub_typ')
        start = request.POST.get('start')
        end = request.POST.get('end')
        reward = request.POST.get('reward')
        prize = request.POST.get('prize')

        Hackathon.objects.create(title=title, desc=desc, sub_typ=sub_typ,
                                 start=start, end=end, reward=reward, prize=prize)

        with open('create/static/'+title+'_bg_img.jpg', 'wb') as destination:
            for chunk in bg_img.chunks():
                destination.write(chunk)

        with open('create/static/'+title+'_hack_img.jpg', 'wb') as destination:
            for chunk in hack_img.chunks():
                destination.write(chunk)

        return redirect('hackathons')

    return render(request, 'create.html')

hackathon/views.py
from hackathon.models import Hackathon
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from home.models import Cart
from submission.models import DataSubmission


def create(request):

    if request.method == 'POST':
        title = request.POST.get('title')
        desc = request.POST.get('desc')
        bg_img = request.FILES['bg_img']
        hack_img = request.FILES['hack_img']
        sub_typ = request.POST.get('sub_typ')
        start = request.POST.get('start')
        end = request.POST.get('end')
        reward = request.POST.get('reward')
        prize = request.POST.get('prize')

        Hackathon.objects.create(title=title, desc=desc, sub_typ=sub_typ,
                                 start=start, end=end, reward=reward, prize=prize)

        with open('static/'+title+'_bg_img.jpg', 'wb') as destination:
            for chunk in bg_img.chunks():
                destination.write(chunk)

        with open('static/'+title+'_hack_img.jpg', 'wb') as destination:
            for chunk in hack_img.chunks():
                destination.write(chunk)

        return redirect('hackathons')

    return render(request, 'create.html')


def hackathons(request):

    hacks = []
    query = Hackathon.objects.all()

    for hack in query:
        if not Cart.objects.filter(user=request.user, hackathon=hack):
            hacks.append(hack)

    return render(request, 'hackathons.html', {'hackathons': hacks})


@login_required
def register_hack(request, hack_id):
    hackathon = get_object_or_404(Hackathon, pk=hack_id)
    cart, created = Cart.objects.get_or_create(user=request.user, hackathon=hackathon)
    if not created:
        cart.save()
    return redirect('hackathons')


@login_required
def my_hackathons(request):
    cart = Cart.objects.filter(user=request.user)

    hacks = []
    for v in cart:
        hack = Hackathon.objects.filter(id=v.hackathon_id).first()
        if DataSubmission.objects.filter(owner=request.user, hack=hack):
            hack.sub_typ = ''
        hacks.append(hack)

    return render(request, 'registered_hacks.html', {'hackathons': hacks})

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout


def home(request):
    context = {
        'isLogin': request.user.username
    }
    return render(request, 'home.html', context)


def custom_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.filter(username=username, password=password).first()
        if user:
            login(request, user)
            return redirect('home')

    return render(request, 'login.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        user = User.objects.filter(username=username).first()
        if user:
            return render(request, 'signup.html')

        User.objects.create(username=username, password=password, email=email)
        return redirect('login')

    return render(request, 'signup.html')


def custom_logout(request):
    logout(request)
    return redirect('login')

templates/create.html
<!doctype html>
<html>
    <head>
        <title>Hackify</title>
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <style>
            .card{
            background-color:rgb(25,25,29)
            }
            body {
              font-family: Arial, sans-serif;
              background-color: #f4f4f4;
            }

            form {
              max-width: 500px;
              margin: 0 auto;
              padding: 20px;
              background-color: #ffffff;
              border-radius: 5px;
              box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            label {
              display: block;
              font-weight: bold;
              margin-bottom: 5px;
            }

            input[type="text"],
            input[type="number"],
            textarea,
            select {
              width: 100%;
              padding: 8px;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
              margin-bottom: 10px;
              font-size: 16px;
            }

            input[type="file"] {
              margin-top: 5px;
            }

            input[type="submit"] {
              background-color: #4CAF50;
              color: #fff;
              padding: 10px 20px;
              border: none;
              border-radius: 4px;
              cursor: pointer;
              font-size: 16px;
            }

            input[type="submit"]:hover {
              background-color: #45a049;
            }

            @media (max-width: 600px) {
              form {
                max-width: 100%;
                margin: 0 auto;
                padding: 10px;
              }

              input[type="submit"] {
                width: 100%;
              }
            }
        </style>
    </head>

    <body style="background-color:#19191d;">
        <!--************                          Navbar component                *********t**********-->
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand text-white" href="/">Hackify</a>
                <div class="">
                    <a href="/hackathons"> <button class="btn btn-outline-success" type="submit">Hackathons</button></a>
                    <a href="/my_hackathons"> <button class="btn btn-outline-success" type="submit">My Hackathons</button> </a>
                    {% if isLogin == '' %}
                    <a href="/login"> <button class="btn btn-outline-success" type="submit">Login</button></a>
                    <a href="/signup"> <button class="btn btn-outline-success" type="submit">Signup</button> </a>
                    {% else %}
                    <a href="/logout"> <button class="btn btn-outline-success" type="submit"> Logout</button> </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <form action="" method="post" enctype="multipart/form-data" class="border-success">
            {% csrf_token %}
            <label for="title">Title:</label>
            <input type="text" id="title" name="title" required>

            <label for="desc">Description:</label>
            <textarea id="desc" name="desc" required></textarea>

            <label for="bg_img">Background Image:</label>
            <input type="file" id="bg_img" name="bg_img" accept="image/*" required>

            <label for="hack_img" style="margin-top:10px">Hackathon Image:</label>
            <input type="file" id="hack_img" name="hack_img" accept="image/*" required>

            <label for="sub_typ" style="margin-top:10px">Submission Type:</label>
            <select id="sub_typ" name="sub_typ" required>
            <option value="img">Image</option>
            <option value="link">Link</option>
            <option value="file">File</option>
            </select>

            <label for="start">Start Date:</label>
            <input type="date" id="start" name="start" required>

            <label for="end" style="margin-top:10px">End Date:</label>
            <input type="date" id="end" name="end" required>

            <label for="reward" style="margin-top:10px">Reward:</label>
            <input type="number" id="reward" name="reward" required>

            <label for="prize">Prize:</label>
            <input type="text" id="prize" name="prize" required>

            <input type="submit" value="Submit">

        </form>

    </body>
</html>

templates/hackathons.html
<!doctype html>
<html>
    <head>
        <title>Hackify</title>
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <style>
            .card{
            background-color:rgb(25,25,29)
            }

            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 20px;
                margin-left: 30px;
                margin-right: 30px;
            }

            h1 {
                text-align: center;
                margin-bottom: 30px;
                color: #ffffff;
            }

            .hackathon-details {
                margin-left: 300px;
                margin-right: 300px;
                margin-bottom: 30px;
                padding: 50px;
                border: 1px solid #ccc;
                border-radius: 5px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            }

            .hackathon-details h2 {
                margin-top: 0;
                font-size: 24px;
                margin-bottom: 10px;
            }

            .hackathon-details p {
                margin: 5px 0;
                font-size: 16px;
            }

            .apply-button {
                text-align: center;
                margin-top: 15px;
            }

            .apply-button a {
                display: inline-block;
                background-color: #4CAF50;
                color: #ffffff;
                padding: 8px 16px;
                text-decoration: none;
                border-radius: 4px;
                font-size: 16px;
            }
        </style>
    </head>

    <body style="background-color:#19191d;">
        <!--************                          Navbar component                *********t**********-->
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand text-white" href="/">Hackify</a>
                <div class="">
                    <a href="/create"> <button class="btn btn-outline-success" type="submit">Create</button> </a>
                    <a href="/my_hackathons"> <button class="btn btn-outline-success" type="submit">My Hackathons</button> </a>
                    {% if isLogin == '' %}
                    <a href="/login"> <button class="btn btn-outline-success" type="submit">Login</button></a>
                    <a href="/signup"> <button class="btn btn-outline-success" type="submit">Signup</button> </a>
                    {% else %}
                    <a href="/logout"> <button class="btn btn-outline-success" type="submit"> Logout</button> </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <h1>Available Hackathons</h1>

        {% for hackathon in hackathons %}
        <div class="hackathon-details border-success text-white">
            <h2 style="text-align: center;">{{ hackathon.title }}</h2>
            <p><strong>Submission Type:</strong> {{ hackathon.sub_typ }}</p>
            <p><strong>Start Date:</strong> {{ hackathon.start }}</p>
            <p><strong>End Date:</strong> {{ hackathon.end }}</p>
            <p><strong>Reward:</strong> {{ hackathon.reward }}</p>
            <p><strong>Prize:</strong> {{ hackathon.prize }}</p>
            <p><strong>Description:</strong></p>
            <p>{{ hackathon.desc }}</p>
            <div class="apply-button">
                <a href="{% url 'register_hack' hack_id=hackathon.id %}">Register</a>
            </div>
        </div>
        {% endfor %}

        {% if not hackathons %}
        <h2 style="text-align:center; margin-top:300px" class="text-white">Wait for new hackathons to participate!</h2>
        {% endif %}

    </body>
</html>

templates/home.html
<!doctype html>
<html>
    <head>
        <title>Hackify</title>
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <style>
            .card{
            background-color:rgb(25,25,29)
            }
        </style>
    </head>
    <body style="background-color:#19191d;">
        <!--************                          Navbar component                *********t**********-->
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand text-white" href="/">Hackify</a>
                <div class="">
                    {% if isLogin == '' %}
                    <a href="/login"> <button class="btn btn-outline-success" type="submit">Login</button></a>
                    <a href="/signup"> <button class="btn btn-outline-success" type="submit">Signup</button> </a>
                    {% else %}
                    <a href="/logout"> <button class="btn btn-outline-success" type="submit"> Logout</button> </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <!--***********************************************                 hero section ****************************************************-->
        <section class=" py-5 py-xl-8 py-xxl-18 h-100 text-white" style="height:100vh; background-color:black">
            <div class="container border-warning overflow-hidden">
                <div class="row gy-5 gy-lg-0">
                    <div class>
                        <h1 class="display-3 fw-bold mb-3">Hackify</h1>
                        <p class="fs-4 mb-5">Are you ready to unleash your creativity and problem-solving skills? Our Hackathon Hosting Website is your
                            platform to participate in exciting hackathons, showcase your talents, and collaborate with like-minded
                            individuals from around the world. Whether you are an experienced developer, designer, or just someone
                            passionate about technology, our hackathons offer you a chance to tackle real-world challenges, build
                            innovative solutions, and network with industry experts and mentors.
                        </p>
                        <div class="d-grid gap-2 d-sm-flex">
                            <a href="/hackathons">
                            <button class="btn btn-primary btn-2xl rounded-pill px-4" type="button">Get Started</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--**********************************************  features section ******************************-->

        <!--**********************************************  features section ******************************-->
        <section>
            <div class="container ">
                <div class="row justify-content-center w-full text-white text-center p-2 mx-auto my-3">
                    <h1>Features</h1>
                </div>
                <div class="row my-2 mb-4">
                    <div class="col ">
                        <div class="cardd card border-primary  mb-3" style="max-width: 18rem;">
                            <div class="card-header text-white">Remote Participation</div>
                            <div class="card-body text-primary">
                                <p class="card-text">Join hackathons from anywhere in the world. No travel required!</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="cardd card border-danger mb-3" style="max-width: 18rem;">
                            <div class="card-header text-white">Expert Mentors</div>
                            <div class="card-body text-danger">
                                <p class="card-text">Get guidance and support from industry experts and mentors.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="cardd card border-success mb-3" style="max-width: 18rem;">
                            <div class="card-header text-white">Creative Challenges</div>
                            <div class="card-body text-success">
                                <p class="card-text">Participate in exciting and challenging hackathon projects.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <style>
            body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            text-align: center;
            }
            .container {
            display: inline-block;
            margin-top: 100px;
            padding: 30px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
            h1 {
            color: #333;
            font-size: 24px;
            margin-bottom: 30px;
            }
            input[type="text"],
            input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 3px;
            box-sizing: border-box;
            }
            input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            }
            input[type="submit"]:hover {
            background-color: #45a049;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <p style="color:red;">{{error}}</p>
            <h1>Login</h1>
            <form action="/login/" method="post">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username" required><br>
                <input type="password" name="password" placeholder="Password" required><br>
                <input type="submit" value="Login">
            </form>
            <div class="signup-link">
                <p>Don't have an account? <a href="/signup">Sign Up</a></p>
            </div>
        </div>
    </body>
</html>

templates/registered_hacks.html
<!doctype html>
<html>
    <head>
        <title>Hackify</title>
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <style>
            .card{
            background-color:rgb(25,25,29)
            }

            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 20px;
                margin-left: 30px;
                margin-right: 30px;
            }

            h1 {
                text-align: center;
                margin-bottom: 30px;
                color: #ffffff;
            }

            .hackathon-details {
                margin-left: 300px;
                margin-right: 300px;
                margin-bottom: 30px;
                padding: 50px;
                border: 1px solid #ccc;
                border-radius: 5px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            }

            .hackathon-details h2 {
                margin-top: 0;
                font-size: 24px;
                margin-bottom: 10px;
            }

            .hackathon-details p {
                margin: 5px 0;
                font-size: 16px;
            }

            .apply-button {
                text-align: center;
                margin-top: 15px;
            }

            .apply-button a {
                display: inline-block;
                background-color: #4CAF50;
                color: #ffffff;
                padding: 8px 16px;
                text-decoration: none;
                border-radius: 4px;
                font-size: 16px;
            }
        </style>
    </head>

    <body style="background-color:#19191d;">
        <!--************                          Navbar component                *********t**********-->
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand text-white" href="/">Hackify</a>
                <div class="">
                    <a href="/view_submissions"> <button class="btn btn-outline-success" type="submit">My Submissions</button></a>
                    <a href="/hackathons"> <button class="btn btn-outline-success" type="submit">Hackathons</button></a>
                    {% if isLogin == '' %}
                    <a href="/login"> <button class="btn btn-outline-success" type="submit">Login</button></a>
                    <a href="/signup"> <button class="btn btn-outline-success" type="submit">Signup</button> </a>
                    {% else %}
                    <a href="/logout"> <button class="btn btn-outline-success" type="submit"> Logout</button> </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <h1>My Hackathons</h1>

        {% for hackathon in hackathons %}
        <div class="hackathon-details border-success text-white">
            <h2 style="text-align: center;">{{ hackathon.title }}</h2>
            <p><strong>Submission Type:</strong> {{ hackathon.sub_typ }}</p>
            <p><strong>Start Date:</strong> {{ hackathon.start }}</p>
            <p><strong>End Date:</strong> {{ hackathon.end }}</p>
            <p><strong>Reward:</strong> {{ hackathon.reward }}</p>
            <p><strong>Prize:</strong> {{ hackathon.prize }}</p>
            <p><strong>Description:</strong></p>
            <p>{{ hackathon.desc }}</p>

            {% if hackathon.sub_typ != '' %}
            <div class="apply-button">
                <a href="{% url 'submit_data' hack_id=hackathon.id %}">Make Submission</a>
            </div>
            {% else %}
            <div class="apply-button">
                <a href="{% url 'submit_data' hack_id=hackathon.id %}">Submitted</a>
            </div>
            {% endif %}
        </div>
        {% endfor %}

    </body>
</html>

templates/submit_data.html
<!doctype html>
<html>
    <head>
        <title>Hackify</title>
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
        <style>
            .card{
            background-color:rgb(25,25,29)
            }
            body {
              font-family: Arial, sans-serif;
              background-color: #f4f4f4;
            }

            form {
              max-width: 500px;
              margin: 0 auto;
              padding: 20px;
              background-color: #ffffff;
              border-radius: 5px;
              box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            label {
              display: block;
              font-weight: bold;
              margin-bottom: 5px;
            }

            input[type="text"],
            input[type="number"],
            textarea,
            select {
              width: 100%;
              padding: 8px;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
              margin-bottom: 10px;
              font-size: 16px;
            }

            input[type="file"] {
              margin-top: 5px;
            }

            input[type="submit"] {
              background-color: #4CAF50;
              color: #fff;
              padding: 10px 20px;
              border: none;
              border-radius: 4px;
              cursor: pointer;
              font-size: 16px;
            }

            input[type="submit"]:hover {
              background-color: #45a049;
            }

            @media (max-width: 600px) {
              form {
                max-width: 100%;
                margin: 0 auto;
                padding: 10px;
              }

              input[type="submit"] {
                width: 100%;
              }
            }
        </style>
    </head>

    <body style="background-color:#19191d;">
        <!--************                          Navbar component                *********t**********-->
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand text-white" href="/">Hackify</a>
                <div class="">
                    <a href="/my_hackathons"> <button class="btn btn-outline-success" type="submit">My Hackathons</button> </a>
                    {% if isLogin == '' %}
                    <a href="/login"> <button class="btn btn-outline-success" type="submit">Login</button></a>
                    <a href="/signup"> <button class="btn btn-outline-success" type="submit">Signup</button> </a>
                    {% else %}
                    <a href="/logout"> <button class="btn btn-outline-success" type="submit"> Logout</button> </a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <form action="" method="post" enctype="multipart/form-data" class="border-success">

            {% csrf_token %}

            <label for="Name">Name:</label>
            <input type="text" id="name" name="name" required>

            <label for="summ">Summary:</label>
            <textarea id="summ" name="summ" required></textarea>

            {% if sub_typ == 'file' %}
            <label for="id_file">File:</label>
            <input type="file" id="id_file" name="file">

            {% elif sub_typ == 'img' %}
            <label for="id_image">Image:</label>
            <input type="file" id="id_image" name="img">

            {% elif sub_typ == 'link' %}
            <label for="id_link">Link:</label>
            <input type="text" id="id_link" name="link">

            {% endif %}

            <input type="submit" value="Submit">

        </form>

    </body>
</html>